### ISSUE TITLE
Git/Contribution/Dev good practices

### ISSUE THREAD

**Issue by jmferreiratech** [LaNoC-UFC/GitHub-roadmap#4]
Add good practices for using git, contributing on a project and general development tips as TDD whenever possible, the refactor-fix/implement-refactor development workflow, the "push code better then you pulled" principle and so on.

**Comment by rmilfont** [comment]
I'll do the best practices section.

**Comment by jmferreiratech** [comment]
This was partially done by #9 and I'll close it.
